Repository gabrieldinizdev/alexandria-backend, pull requests merged in 2024-08, with the labels that each got.

#15 [ FEATURE ] Add reset password
  .docker/docker-compose.yml
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dtos/index.ts
  src/modules/auth/dtos/reset-password.dto.ts
  src/modules/auth/dtos/verification-code.dto.ts
  src/modules/auth/types/index.ts
  src/modules/auth/types/nodemailer.ts
  src/modules/auth/types/redis.ts
  src/modules/modules.module.ts
  src/modules/redis/redis.module.ts
  src/modules/redis/redis.service.ts
  src/shared/utils/generate-code.ts
  src/shared/utils/index.ts
  src/templates/auth/forgot-password.template.ts
  src/templates/auth/index.ts
Labels: enhancement

#16 [ FEATURE ] add sign-up
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dtos/sign-up.dto.ts
  src/modules/auth/responses/index.ts
  src/modules/auth/responses/reset-password.dto.ts
  src/modules/auth/responses/sign-up-response.dto.ts
  src/modules/auth/responses/verification-code-response.dto.ts
  src/modules/customer/customer.service.ts
  src/modules/product/product.service.ts
  src/shared/responses/common/conflict.dto.ts
  src/shared/responses/common/index.ts
Labels: enhancement

#17 [ FEATURE ] Readme Alias Port to Docker Images
  README.md
Labels: documentation

#14 [ FEATURE ] Custom Exception Filters
  src/main.ts
  src/shared/filters/http-exception/http-exception.filter.ts
  src/shared/filters/http-exception/index.ts
  src/shared/providers/prisma-error-handler/index.ts
  src/shared/providers/prisma-error-handler/prisma-error-handler.ts
  src/shared/shared.module.ts
  src/shared/types/error-response.type.ts
  src/shared/types/index.ts
  src/shared/utils/prisma-known-exception-status.ts
Labels: feature
